#!/bin/bash

set -e

export current_branch=`git rev-parse --abbrev-ref HEAD`

if [ "$current_branch" != "master" ]; then
  echo -e "\e[31mCurrent branch is \"$current_branch\" not master - exiting\e[39m"
  exit 1
fi

git branch --merged | egrep -v "(^\*|master|dev)" | xargs --no-run-if-empty git branch -d && \
	echo -e "\e[32mok\e[39m" || echo "\e[31mfail\e[39m"

